Posts Administracion cooperativa
fiqus/fiqus-web-front pull request #11
Opened 2022-01-17 20:23 UTC by MJoaaquin

Agregando los posts administracion de cooperativas parte 1, 2 y 3

2022-01-17 20:28 UTC, MJoaaquin commented
Esta imagen no la pude descargar http://blog.fiqus.webfactional.com/wp-content/uploads/2014/01/anticipo1.png asi que la vole, si alguno sabe la subimos

2022-01-17 20:40 UTC, diegomanuel requested changes
Está joyaaa lo único faltante serían los adjuntos que indiqué!

2022-01-17 20:40 UTC, diegomanuel commented on src/content/posts/es/administracion-de-cooperativas-1.md
> +[caja y banco (formato xlsx)]("http://blog.fiqus.webfactional.com/wp-content/uploads/2013/07/caja_y_banco.xlsx")
Habría que tratar de conseguir y adjuntar tmb estos archivos! :sweat_smile:

2022-01-17 20:40 UTC, diegomanuel commented on src/content/posts/es/administracion-de-cooperativas-1.md
> +[cc_cliente (formato xlsx)](http://blog.fiqus.webfactional.com/wp-content/uploads/2013/07/cc_cliente.xlsx)
Habría que tratar de conseguir y adjuntar tmb estos archivos! :sweat_smile:

2022-01-17 20:40 UTC, diegomanuel commented on src/content/posts/es/administracion-de-cooperativas-2.md
> +[Finanzas (formato .xlsx)](http://blog.fiqus.webfactional.com/wp-content/uploads/2013/10/Finanzas.xlsx)
Habría que tratar de conseguir y adjuntar tmb estos archivos! :sweat_smile:

2022-01-17 20:40 UTC, diegomanuel commented on src/content/posts/es/administracion-de-cooperativas-3.md
> +[matriz (formato xlsx)](http://blog.fiqus.webfactional.com/wp-content/uploads/2014/01/matriz.xlsx)
Habría que tratar de conseguir y adjuntar tmb estos archivos! :sweat_smile:

2022-01-18 19:35 UTC, MJoaaquin commented on src/content/posts/es/administracion-de-cooperativas-1.md
> +[caja y banco (formato xlsx)]("http://blog.fiqus.webfactional.com/wp-content/uploads/2013/07/caja_y_banco.xlsx")
@diegomanuel Los saque hasta que los podamos conseguir

2022-01-18 19:35 UTC, MJoaaquin commented on src/content/posts/es/administracion-de-cooperativas-1.md
> +[cc_cliente (formato xlsx)](http://blog.fiqus.webfactional.com/wp-content/uploads/2013/07/cc_cliente.xlsx)
lo mismo por aqui @diegomanuel

2022-01-18 19:36 UTC, MJoaaquin commented on src/content/posts/es/administracion-de-cooperativas-2.md
> +[Finanzas (formato .xlsx)](http://blog.fiqus.webfactional.com/wp-content/uploads/2013/10/Finanzas.xlsx)
aca tambien lo saque

2022-01-18 19:36 UTC, MJoaaquin commented on src/content/posts/es/administracion-de-cooperativas-3.md
> +[matriz (formato xlsx)](http://blog.fiqus.webfactional.com/wp-content/uploads/2014/01/matriz.xlsx)
y aqui tambien los vole @diegomanuel

2022-01-18 20:16 UTC, diegomanuel approved these changes

2022-01-19 13:41 UTC, merged