Add Erlang and Elixir with asdf post
fiqus/fiqus-web-front pull request #29
Opened 2022-01-24 14:21 UTC by pbrudnick

2022-01-25 15:00 UTC, nicolasdimarco commented on src/content/posts/es/instalando-earlang-y-elixir-con-asdf.md
> +2. Luego agregamos plugin de Erlang y de Elixir:
al probarlo muestra todos los puntos como "1."

2022-01-26 13:09 UTC, pbrudnick commented on src/content/posts/es/instalando-earlang-y-elixir-con-asdf.md
> +2. Luego agregamos plugin de Erlang y de Elixir:
lo veo bien yo:
<img width="459" alt="Captura de Pantalla 2022-01-26 a la(s) 10 09 03" src="https://user-images.githubusercontent.com/896524/151168615-c23f1174-b184-4666-99f2-af193f993c88.png">

2022-01-26 13:50 UTC, JeronimoC23 requested changes

2022-01-26 13:50 UTC, JeronimoC23 commented on src/content/posts/es/instalando-earlang-y-elixir-con-asdf.md
> +
Entre el 2 y 3 quiza agregaria un <br> porque con los ``` aveces no interpreta los espacios yo ahora lo veo asi: 
![image](https://user-images.githubusercontent.com/66791971/151174769-50af8af4-5856-4b63-af8e-698d00a68708.png)

Y con un br me queda:
![image](https://user-images.githubusercontent.com/66791971/151174866-455a931f-0b11-4624-a291-f0d3f26bbd1c.png)

2022-01-26 13:57 UTC, pbrudnick commented on src/content/posts/es/instalando-earlang-y-elixir-con-asdf.md
> +
listo, gracias, no tomaba espacios ni mas enters directo sin html :S

2022-01-26 15:22 UTC, JeronimoC23 approved these changes

2022-01-26 15:35 UTC, merged