Como instalar django en ubuntu
fiqus/fiqus-web-front pull request #32
Opened 2022-01-24 19:40 UTC by JeronimoC23

2022-01-24 20:36 UTC, pbrudnick requested changes

2022-01-24 20:36 UTC, pbrudnick commented on src/content/posts/es/instalar-django-ubuntu.md
> +pip freeze &gt; requirements.txt
```suggestion
pip freeze > requirements.txt
```

2022-01-25 14:55 UTC, nicolasdimarco commented on src/content/posts/es/instalar-django-ubuntu.md
> +[Django](https://www.djangoproject.com/") es un framework de desarrollo web de código abierto, escrito en Python, que cumple en cierta medida el paradigma del Modelo Vista Controlador ([Wiki](http://
Sacar comillas de más => https://www.djangoproject.com/"

2022-01-26 19:20 UTC, pbrudnick approved these changes

2022-01-27 13:44 UTC, merged